target: 적용 공법

methods:
  - NATM
  - EPB TBM
  - Slurry TBM
  - 개착식
  - 침매식

exclude_features:
  - 사례명
  - 선형
  - 지하수
  - 지하수 조건
  - 지하수 조건_정규화

numeric_features:
  - 심도(m)_정규화
  - 구경(m)_정규화
  - 터널 길이(km)_정규화

categorical_features:
  - 지반 조건_정규화
  - 시공 위치_정규화
  - 주변 민감도_정규화
  - 요구사항_주요정규화
  - 요구사항_보조정규화

required_columns:
  - 사례명
  - 적용 공법
  - 지반 조건_정규화
  - 시공 위치_정규화
  - 심도(m)_정규화
  - 구경(m)_정규화
  - 주변 민감도_정규화
  - 요구사항_주요정규화
  - 요구사항_보조정규화
  - 터널 길이(km)_정규화